export const AUTH_USER = 'AUTH_USER';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_RESET = 'AUTH_RESET';


export const SEARCH = 'SEARCH';
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const GET_ALL_LAW = 'GET_ALL_LAW';
export const GET_ALL_LAW_START = 'GET_ALL_LAW_START';
export const GET_ALL_LAW_SUCCESS = 'GET_ALL_LAW_SUCCESS';
export const GET_ALL_LAW_FAIL = 'GET_ALL_LAW_FAIL';

export const GET_LAW_DETAIL = 'GET_LAW_DETAIL';
export const GET_LAW_DETAIL_START = 'GET_LAW_DETAIL_START';
export const GET_LAW_DETAIL_SUCCESS = 'GET_LAW_DETAIL_SUCCESS';
export const GET_LAW_DETAIL_FAIL = 'GET_LAW_DETAIL_FAIL';

export const GET_LIST_AGENCY = 'GET_LIST_AGENCY';
export const GET_LIST_AGENCY_START = 'GET_LIST_AGENCY_START';
export const GET_LIST_AGENCY_SUCCESS = 'GET_LIST_AGENCY_SUCCESS';
export const GET_LIST_AGENCY_FAIL = 'GET_LIST_AGENCY_FAIL';

export const GET_VALIDITY_STATUS_LIST = 'GET_VALIDITY_STATUSES';
export const GET_VALIDITY_STATUS_LIST_START = 'GET_VALIDITY_STATUSES_START';
export const GET_VALIDITY_STATUS_LIST_FAIL = 'GET_VALIDITY_STATUSES_FAIL';
export const GET_VALIDITY_STATUS_LIST_SUCESS = 'GET_VALIDITY_STATUSES_SUCESS';

export const GET_LAW_CLASS_LIST = 'GET_LAW_CLASS_LIST';
export const GET_LAW_CLASS_LIST_START = 'GET_LAW_CLASS_LIST_START';
export const GET_LAW_CLASS_LIST_SUCCESS = 'GET_LAW_CLASS_LIST_SUCCESS';
export const GET_LAW_CLASS_LIST_FAIL = 'GET_LAW_CLASS_LIST_FAIL';

export const GET_NEWEST_LAW = 'GET_NEWEST_LAW';
export const GET_NEWEST_LAW_START = 'GET_NEWEST_LAW_START';
export const GET_NEWEST_LAW_SUCCESS = 'GET_NEWEST_LAW_SUCCESS';
export const GET_NEWEST_LAW_FAIL = 'GET_NEWEST_LAW_FAIL';

export const GET_MOST_VIEWED_LAW = 'GET_MOST_VIEWED_LAW';
export const GET_MOST_VIEWED_LAW_START = 'GET_MOST_VIEWED_LAW_START';
export const GET_MOST_VIEWED_LAW_SUCCESS = 'GET_MOST_VIEWED_LAW_SUCCESS';
export const GET_MOST_VIEWED_LAW_FAIL = 'GET_MOST_VIEWED_LAW_FAIL';

export const GET_MOST_VIEWED_NEW = 'GET_MOST_VIEWED_NEW';
export const GET_MOST_VIEWED_NEW_START = 'GET_MOST_VIEWED_NEW_START';
export const GET_MOST_VIEWED_NEW_SUCCESS = 'GET_MOST_VIEWED_NEW_SUCCESS';
export const GET_MOST_VIEWED_NEW_FAIL = 'GET_MOST_VIEWED_NEW_FAIL';

export const GET_ALL_NEWS = 'GET_ALL_NEWS';
export const GET_ALL_NEWS_START = 'GET_ALL_NEWS_START';
export const GET_ALL_NEWS_SUCCESS = 'GET_ALL_NEWS_SUCCESS';
export const GET_ALL_NEWS_FAIL = 'GET_ALL_NEWS_FAIL';

export const GET_NEWS_BY_ID = 'GET_NEWS_BY_ID';
export const GET_NEWS_BY_ID_START = 'GET_NEWS_BY_ID_START';
export const GET_NEWS_BY_ID_SUCCESS = 'GET_NEWS_BY_ID_SUCCESS';
export const GET_NEWS_BY_ID_FAIL = 'GET_NEWS_BY_ID_FAIL';

export const GET_STEP_SET_BY_INPUT = 'GET_STEP_SET_BY_INPUT';
export const GET_STEP_SET_BY_INPUT_START = 'GET_STEP_SET_BY_INPUT_START';
export const GET_STEP_SET_BY_INPUT_SUCCESS = 'GET_STEP_SET_BY_INPUT_SUCCESS';
export const GET_STEP_SET_BY_INPUT_FAIL = 'GET_STEP_SET_BY_INPUT_FAIL';
export const UPDATE_SET_FEATURE_BY_ID_AND_INPUT = 'UPDATE_SET_FEATURE_BY_ID_AND_INPUT';
export const UPDATE_SET_FEATURE_BY_ID_AND_INPUT_START = 'UPDATE_SET_FEATURE_BY_ID_AND_INPUT_START';
export const UPDATE_SET_FEATURE_BY_ID_AND_INPUT_SUCCESS = 'UPDATE_SET_FEATURE_BY_ID_AND_INPUT_SUCCESS';
export const UPDATE_SET_FEATURE_BY_ID_AND_INPUT_FAIL = 'UPDATE_SET_FEATURE_BY_ID_AND_INPUT_FAIL';
export const RESET_CHAT_BOT = 'RESET_CHAT_BOT';
