export const AUTH_USER = "AUTH_USER";
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";

export const SEARCH = "SEARCH";
export const SEARCH_START = "SEARCH_START";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAIL = "SEARCH_FAIL";

export const GET_LIST_CHAPTER = "GET_LAW";
export const GET_LIST_CHAPTER_START = "GET_LIST_CHAPTER_START";
export const GET_LIST_CHAPTER_SUCCESS = "GET_LIST_CHAPTER_SUCCESS";
export const GET_LIST_CHAPTER_FAIL = "GET_LIST_CHAPTER_FAIL";

export const GET_CHAPTER_DETAIL = "GET_CHAPTER_DETAIL";
export const GET_CHAPTER_DETAIL_START = "GET_CHAPTER_DETAIL_START";
export const GET_CHAPTER_DETAIL_SUCCESS = "GET_CHAPTER_DETAIL_SUCCESS";
export const GET_CHAPTER_DETAIL_FAIL = "GET_CHAPTER_DETAIL_FAIL";

export const GET_ALL_NEWS = "GET_ALL_NEWS";
export const GET_ALL_NEWS_START = "GET_ALL_NEWS_START";
export const GET_ALL_NEWS_SUCCESS = "GET_ALL_NEWS_SUCCESS";
export const GET_ALL_NEWS_FAIL = "GET_ALL_NEWS_FAIL";
export const TO_NEWS_DETAIL = "TO_NEWS_DETAIL";
